# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Spotichris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotichris
  # Aucune dépendance externe requise pour CarPlay (framework natif)

end







